language: php
sudo: false
cache:
  apt: true

php:
    - 7.2
    - 7.3
before_script:
    - composer install
script:
    - vendor/bin/codecept run --coverage --coverage-xml --coverage-html
after_script:
    - if [ $TRAVIS_PHP_VERSION == '7.2' ]; then php vendor/bin/coveralls; fi
after_success:
    - travis_retry php vendor/bin/coveralls -v


