language: php
sudo: false
cache:
  apt: true

php:
  - 7.3
  - 7.4
  - 8.0
before_script:
  - composer install
script:
  - export XDEBUG_MODE=coverage
  - vendor/bin/codecept run --coverage --coverage-xml --coverage-html
after_script:
  - if [ $TRAVIS_PHP_VERSION == '7.4' ]; then php vendor/bin/php-coveralls; fi
after_success:
  - travis_retry php vendor/bin/php-coveralls -v


